name: 'my first container ation'
description: 'Love you!!!'
author: 'Foluke M."
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: "Awesome bro!'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
